// 展厅基础信息配置，可全局复用
export const halls = [
  {
    id: 73,
    name: '启风山谷',
    enName: 'First Whisper',
    subTitle: 'Chasing the Wind',
    enSubTitle: 'Chasing the Wind',
    desc: '启风山谷展厅简介',
    enDesc: 'Introduction of First Whisper Hall',
    color: '#2FA3B0',
    icon: import.meta.env.BASE_URL + 'assets/images/halls/hall-icons/icon73.png',
    logo: import.meta.env.BASE_URL + 'assets/images/halls/hall-logos/hall-73.png',
    border: import.meta.env.BASE_URL + 'assets/images/halls/hall-borders/border73.png',
  },
  {
    id: 74,
    name: '穿林探径',
    enName: 'Unveiled Horizons',
    subTitle: 'Chasing the Wind',
    enSubTitle: 'Chasing the Wind',
    desc: '驰风原野展厅简介',
    enDesc: 'Introduction of Unveiled Horizons Hall',
    color: '#6CB130',
    icon: import.meta.env.BASE_URL + 'assets/images/halls/hall-icons/icon74.png',
    logo: import.meta.env.BASE_URL + 'assets/images/halls/hall-logos/hall-74.png',
    border: import.meta.env.BASE_URL + 'assets/images/halls/hall-borders/border74.png',
  },
  {
    id: 75,
    name: '驰风原野',
    enName: 'Fusion Cosmos',
    subTitle: 'Chasing the Wind',
    enSubTitle: 'Chasing the Wind',
    desc: '融和万象展厅简介',
    enDesc: 'Introduction of Fusion Cosmos Hall',
    color: '#F5A623',
    icon: import.meta.env.BASE_URL + 'assets/images/halls/hall-icons/icon75.png',
    logo: import.meta.env.BASE_URL + 'assets/images/halls/hall-logos/hall-75.png',
    border: import.meta.env.BASE_URL + 'assets/images/halls/hall-borders/border75.png',
  },
  {
    id: 76,
    name: '掠泽听声',
    enName: 'Infinite Colors',
    subTitle: 'Chasing the Wind',
    enSubTitle: 'Chasing the Wind',
    desc: '掠泽听声展厅简介',
    enDesc: 'Introduction of Infinite Colors Hall',
    color: '#7B61FF',
    icon: import.meta.env.BASE_URL + 'assets/images/halls/hall-icons/icon76.png',
    logo: import.meta.env.BASE_URL + 'assets/images/halls/hall-logos/hall-76.png',
    border: import.meta.env.BASE_URL + 'assets/images/halls/hall-borders/border76.png',
  },
  {
    id: 77,
    name: '终风化木',
    enName: 'Rising Stars',
    subTitle: 'Chasing the Wind',
    enSubTitle: 'Chasing the Wind',
    desc: '终风化木展厅简介',
    enDesc: 'Introduction of Rising Stars Hall',
    color: '#FF6F61',
    icon: import.meta.env.BASE_URL + 'assets/images/halls/hall-icons/icon77.png',
    logo: import.meta.env.BASE_URL + 'assets/images/halls/hall-logos/hall-77.png',
    border: import.meta.env.BASE_URL + 'assets/images/halls/hall-borders/border77.png',
  }
]
